/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewIndexRouteImport } from './routes/review/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as SettingsMemoryRouteImport } from './routes/settings/memory'
import { Route as SettingsConnectionsRouteImport } from './routes/settings/connections'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as HandlerSplatRouteImport } from './routes/handler/$'
import { Route as ChatSettingsRouteImport } from './routes/chat/settings'
import { Route as ChatChatIdRouteImport } from './routes/chat/$chatId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdChatChatIdRouteImport } from './routes/projects/$projectId/chat/$chatId'
import { Route as ReviewKindOwnerRepoNumberRouteImport } from './routes/review/$kind.$owner.$repo.$number'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsMemoryRoute = SettingsMemoryRouteImport.update({
  id: '/settings/memory',
  path: '/settings/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/settings/connections',
  path: '/settings/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const HandlerSplatRoute = HandlerSplatRouteImport.update({
  id: '/handler/$',
  path: '/handler/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => ChatRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdChatChatIdRoute =
  ProjectsProjectIdChatChatIdRouteImport.update({
    id: '/chat/$chatId',
    path: '/chat/$chatId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ReviewKindOwnerRepoNumberRoute =
  ReviewKindOwnerRepoNumberRouteImport.update({
    id: '/$kind/$owner/$repo/$number',
    path: '/$kind/$owner/$repo/$number',
    getParentRoute: () => ReviewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/notes': typeof NotesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/review': typeof ReviewRouteWithChildren
  '/chat/$chatId': typeof ChatChatIdRoute
  '/chat/settings': typeof ChatSettingsRoute
  '/handler/$': typeof HandlerSplatRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/chat/': typeof ChatIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/chat/$chatId': typeof ProjectsProjectIdChatChatIdRoute
  '/review/$kind/$owner/$repo/$number': typeof ReviewKindOwnerRepoNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes': typeof NotesRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/chat/settings': typeof ChatSettingsRoute
  '/handler/$': typeof HandlerSplatRoute
  '/projects/new': typeof ProjectsNewRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/chat': typeof ChatIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/review': typeof ReviewIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/chat/$chatId': typeof ProjectsProjectIdChatChatIdRoute
  '/review/$kind/$owner/$repo/$number': typeof ReviewKindOwnerRepoNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/notes': typeof NotesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/review': typeof ReviewRouteWithChildren
  '/chat/$chatId': typeof ChatChatIdRoute
  '/chat/settings': typeof ChatSettingsRoute
  '/handler/$': typeof HandlerSplatRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/chat/': typeof ChatIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/chat/$chatId': typeof ProjectsProjectIdChatChatIdRoute
  '/review/$kind/$owner/$repo/$number': typeof ReviewKindOwnerRepoNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/notes'
    | '/projects'
    | '/review'
    | '/chat/$chatId'
    | '/chat/settings'
    | '/handler/$'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/connections'
    | '/settings/memory'
    | '/chat/'
    | '/projects/'
    | '/review/'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/chat/$chatId'
    | '/review/$kind/$owner/$repo/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notes'
    | '/chat/$chatId'
    | '/chat/settings'
    | '/handler/$'
    | '/projects/new'
    | '/settings/connections'
    | '/settings/memory'
    | '/chat'
    | '/projects'
    | '/review'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/chat/$chatId'
    | '/review/$kind/$owner/$repo/$number'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/notes'
    | '/projects'
    | '/review'
    | '/chat/$chatId'
    | '/chat/settings'
    | '/handler/$'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/connections'
    | '/settings/memory'
    | '/chat/'
    | '/projects/'
    | '/review/'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/chat/$chatId'
    | '/review/$kind/$owner/$repo/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  NotesRoute: typeof NotesRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReviewRoute: typeof ReviewRouteWithChildren
  HandlerSplatRoute: typeof HandlerSplatRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsMemoryRoute: typeof SettingsMemoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/memory': {
      id: '/settings/memory'
      path: '/settings/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof SettingsMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/handler/$': {
      id: '/handler/$'
      path: '/handler/$'
      fullPath: '/handler/$'
      preLoaderRoute: typeof HandlerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/settings': {
      id: '/chat/settings'
      path: '/settings'
      fullPath: '/chat/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/chat/$chatId': {
      id: '/projects/$projectId/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/projects/$projectId/chat/$chatId'
      preLoaderRoute: typeof ProjectsProjectIdChatChatIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/review/$kind/$owner/$repo/$number': {
      id: '/review/$kind/$owner/$repo/$number'
      path: '/$kind/$owner/$repo/$number'
      fullPath: '/review/$kind/$owner/$repo/$number'
      preLoaderRoute: typeof ReviewKindOwnerRepoNumberRouteImport
      parentRoute: typeof ReviewRoute
    }
  }
}

interface ChatRouteChildren {
  ChatChatIdRoute: typeof ChatChatIdRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatChatIdRoute: ChatChatIdRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdChatChatIdRoute: typeof ProjectsProjectIdChatChatIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdChatChatIdRoute: ProjectsProjectIdChatChatIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ReviewRouteChildren {
  ReviewIndexRoute: typeof ReviewIndexRoute
  ReviewKindOwnerRepoNumberRoute: typeof ReviewKindOwnerRepoNumberRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewIndexRoute: ReviewIndexRoute,
  ReviewKindOwnerRepoNumberRoute: ReviewKindOwnerRepoNumberRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  NotesRoute: NotesRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReviewRoute: ReviewRouteWithChildren,
  HandlerSplatRoute: HandlerSplatRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsMemoryRoute: SettingsMemoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
