/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewIndexRouteImport } from './routes/review/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as SettingsConnectionsRouteImport } from './routes/settings/connections'
import { Route as HandlerSplatRouteImport } from './routes/handler/$'
import { Route as AgentSettingsRouteImport } from './routes/agent/settings'
import { Route as AgentNewRouteImport } from './routes/agent/new'
import { Route as AgentProjectIdRouteImport } from './routes/agent/$projectId'
import { Route as AgentProjectIdSettingsRouteImport } from './routes/agent/$projectId/settings'
import { Route as AgentProjectIdTabsRouteImport } from './routes/agent/$projectId/_tabs'
import { Route as AgentProjectIdTabsIndexRouteImport } from './routes/agent/$projectId/_tabs/index'
import { Route as ReviewKindOwnerRepoNumberRouteImport } from './routes/review/$kind.$owner.$repo.$number'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRoute,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/settings/connections',
  path: '/settings/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const HandlerSplatRoute = HandlerSplatRouteImport.update({
  id: '/handler/$',
  path: '/handler/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSettingsRoute = AgentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AgentRoute,
} as any)
const AgentNewRoute = AgentNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AgentRoute,
} as any)
const AgentProjectIdRoute = AgentProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AgentRoute,
} as any)
const AgentProjectIdSettingsRoute = AgentProjectIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AgentProjectIdRoute,
} as any)
const AgentProjectIdTabsRoute = AgentProjectIdTabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => AgentProjectIdRoute,
} as any)
const AgentProjectIdTabsIndexRoute = AgentProjectIdTabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentProjectIdTabsRoute,
} as any)
const ReviewKindOwnerRepoNumberRoute =
  ReviewKindOwnerRepoNumberRouteImport.update({
    id: '/$kind/$owner/$repo/$number',
    path: '/$kind/$owner/$repo/$number',
    getParentRoute: () => ReviewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/chat': typeof ChatRoute
  '/memory': typeof MemoryRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/review': typeof ReviewRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/agent/$projectId': typeof AgentProjectIdTabsRouteWithChildren
  '/agent/new': typeof AgentNewRoute
  '/agent/settings': typeof AgentSettingsRoute
  '/handler/$': typeof HandlerSplatRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/agent/': typeof AgentIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/agent/$projectId/settings': typeof AgentProjectIdSettingsRoute
  '/agent/$projectId/': typeof AgentProjectIdTabsIndexRoute
  '/review/$kind/$owner/$repo/$number': typeof ReviewKindOwnerRepoNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/memory': typeof MemoryRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/workflows': typeof WorkflowsRoute
  '/agent/$projectId': typeof AgentProjectIdTabsIndexRoute
  '/agent/new': typeof AgentNewRoute
  '/agent/settings': typeof AgentSettingsRoute
  '/handler/$': typeof HandlerSplatRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/agent': typeof AgentIndexRoute
  '/review': typeof ReviewIndexRoute
  '/agent/$projectId/settings': typeof AgentProjectIdSettingsRoute
  '/review/$kind/$owner/$repo/$number': typeof ReviewKindOwnerRepoNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/chat': typeof ChatRoute
  '/memory': typeof MemoryRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/review': typeof ReviewRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/agent/$projectId': typeof AgentProjectIdRouteWithChildren
  '/agent/new': typeof AgentNewRoute
  '/agent/settings': typeof AgentSettingsRoute
  '/handler/$': typeof HandlerSplatRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/agent/': typeof AgentIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/agent/$projectId/_tabs': typeof AgentProjectIdTabsRouteWithChildren
  '/agent/$projectId/settings': typeof AgentProjectIdSettingsRoute
  '/agent/$projectId/_tabs/': typeof AgentProjectIdTabsIndexRoute
  '/review/$kind/$owner/$repo/$number': typeof ReviewKindOwnerRepoNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/chat'
    | '/memory'
    | '/notes'
    | '/onboarding'
    | '/projects'
    | '/review'
    | '/workflows'
    | '/agent/$projectId'
    | '/agent/new'
    | '/agent/settings'
    | '/handler/$'
    | '/settings/connections'
    | '/agent/'
    | '/review/'
    | '/agent/$projectId/settings'
    | '/agent/$projectId/'
    | '/review/$kind/$owner/$repo/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/memory'
    | '/notes'
    | '/onboarding'
    | '/projects'
    | '/workflows'
    | '/agent/$projectId'
    | '/agent/new'
    | '/agent/settings'
    | '/handler/$'
    | '/settings/connections'
    | '/agent'
    | '/review'
    | '/agent/$projectId/settings'
    | '/review/$kind/$owner/$repo/$number'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/chat'
    | '/memory'
    | '/notes'
    | '/onboarding'
    | '/projects'
    | '/review'
    | '/workflows'
    | '/agent/$projectId'
    | '/agent/new'
    | '/agent/settings'
    | '/handler/$'
    | '/settings/connections'
    | '/agent/'
    | '/review/'
    | '/agent/$projectId/_tabs'
    | '/agent/$projectId/settings'
    | '/agent/$projectId/_tabs/'
    | '/review/$kind/$owner/$repo/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRouteWithChildren
  ChatRoute: typeof ChatRoute
  MemoryRoute: typeof MemoryRoute
  NotesRoute: typeof NotesRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRoute
  ReviewRoute: typeof ReviewRouteWithChildren
  WorkflowsRoute: typeof WorkflowsRoute
  HandlerSplatRoute: typeof HandlerSplatRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handler/$': {
      id: '/handler/$'
      path: '/handler/$'
      fullPath: '/handler/$'
      preLoaderRoute: typeof HandlerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/settings': {
      id: '/agent/settings'
      path: '/settings'
      fullPath: '/agent/settings'
      preLoaderRoute: typeof AgentSettingsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/new': {
      id: '/agent/new'
      path: '/new'
      fullPath: '/agent/new'
      preLoaderRoute: typeof AgentNewRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/$projectId': {
      id: '/agent/$projectId'
      path: '/$projectId'
      fullPath: '/agent/$projectId'
      preLoaderRoute: typeof AgentProjectIdRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/$projectId/settings': {
      id: '/agent/$projectId/settings'
      path: '/settings'
      fullPath: '/agent/$projectId/settings'
      preLoaderRoute: typeof AgentProjectIdSettingsRouteImport
      parentRoute: typeof AgentProjectIdRoute
    }
    '/agent/$projectId/_tabs': {
      id: '/agent/$projectId/_tabs'
      path: ''
      fullPath: '/agent/$projectId'
      preLoaderRoute: typeof AgentProjectIdTabsRouteImport
      parentRoute: typeof AgentProjectIdRoute
    }
    '/agent/$projectId/_tabs/': {
      id: '/agent/$projectId/_tabs/'
      path: '/'
      fullPath: '/agent/$projectId/'
      preLoaderRoute: typeof AgentProjectIdTabsIndexRouteImport
      parentRoute: typeof AgentProjectIdTabsRoute
    }
    '/review/$kind/$owner/$repo/$number': {
      id: '/review/$kind/$owner/$repo/$number'
      path: '/$kind/$owner/$repo/$number'
      fullPath: '/review/$kind/$owner/$repo/$number'
      preLoaderRoute: typeof ReviewKindOwnerRepoNumberRouteImport
      parentRoute: typeof ReviewRoute
    }
  }
}

interface AgentProjectIdTabsRouteChildren {
  AgentProjectIdTabsIndexRoute: typeof AgentProjectIdTabsIndexRoute
}

const AgentProjectIdTabsRouteChildren: AgentProjectIdTabsRouteChildren = {
  AgentProjectIdTabsIndexRoute: AgentProjectIdTabsIndexRoute,
}

const AgentProjectIdTabsRouteWithChildren =
  AgentProjectIdTabsRoute._addFileChildren(AgentProjectIdTabsRouteChildren)

interface AgentProjectIdRouteChildren {
  AgentProjectIdTabsRoute: typeof AgentProjectIdTabsRouteWithChildren
  AgentProjectIdSettingsRoute: typeof AgentProjectIdSettingsRoute
}

const AgentProjectIdRouteChildren: AgentProjectIdRouteChildren = {
  AgentProjectIdTabsRoute: AgentProjectIdTabsRouteWithChildren,
  AgentProjectIdSettingsRoute: AgentProjectIdSettingsRoute,
}

const AgentProjectIdRouteWithChildren = AgentProjectIdRoute._addFileChildren(
  AgentProjectIdRouteChildren,
)

interface AgentRouteChildren {
  AgentProjectIdRoute: typeof AgentProjectIdRouteWithChildren
  AgentNewRoute: typeof AgentNewRoute
  AgentSettingsRoute: typeof AgentSettingsRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentProjectIdRoute: AgentProjectIdRouteWithChildren,
  AgentNewRoute: AgentNewRoute,
  AgentSettingsRoute: AgentSettingsRoute,
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface ReviewRouteChildren {
  ReviewIndexRoute: typeof ReviewIndexRoute
  ReviewKindOwnerRepoNumberRoute: typeof ReviewKindOwnerRepoNumberRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewIndexRoute: ReviewIndexRoute,
  ReviewKindOwnerRepoNumberRoute: ReviewKindOwnerRepoNumberRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRouteWithChildren,
  ChatRoute: ChatRoute,
  MemoryRoute: MemoryRoute,
  NotesRoute: NotesRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRoute,
  ReviewRoute: ReviewRouteWithChildren,
  WorkflowsRoute: WorkflowsRoute,
  HandlerSplatRoute: HandlerSplatRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
